### ISSUE TITLE
Change Query Param to Accept Typed Objects

### ISSUE THREAD

**Issue by SIDANWhatever** [maestro-org/typescript-sdk#18]
## Problem
When using the SDK for calling specific endpoints with customized query param, it has a hard time to just pass in one desired query param as it has to follow the specific orders. For example if I only want to restrict the number of `utxos` returned by `Address UTxO`, I have to do something like this, which is really annoying:

```ts
maestroClient.addresses.utxosByAddress(address, undefined, undefined, 100);
```

## Possible Solution
To change all query param with an object, where the query param `key` to be the object key and the query param `value` to be the object value

```ts
maestroClient.addresses.utxosByAddress(address, {count: 100});
```

It is also good to make the query param object typed with default value same as the actual api behaviour.

## Side Note
- If I understand the SDK correctly, `this.maestroClient.addresses.utxosByAddress` equal to [this endpoint](https://docs.gomaestro.org/docs/Indexer-API/Addresses/utxos-by-address), while the SDK has not updated yet to accept `asset` as parameter.
- As this is a systematic breaking change, I might better only contribute after the decision is made.

**Comment by Vardominator** [comment]
@SIDANWhatever We have brought this up internally and know that it's a problem. Please go ahead and proceed with this change. It will be tremendously helpful.
